from __future__ import annotations

from typing import Protocol


class Logger(Protocol):
    def info(self, message: str, **kwargs: object) -> None: ...
    def warning(self, message: str, **kwargs: object) -> None: ...
    def error(self, message: str, **kwargs: object) -> None: ...
    def debug(self, message: str, **kwargs: object) -> None: ...
